import type { AnalyticsBucket, AnalyticsPeriod, ConversationChannel, UsageKind } from "@/features/analytics/types";

export const DEFAULT_ANALYTICS_PERIOD: AnalyticsPeriod = "30d";

export const PERIOD_META: Record<AnalyticsPeriod, { label: string; shortLabel: string; days: number; bucket: AnalyticsBucket }> = {
  "7d": { label: "Last 7 days", shortLabel: "7d", days: 7, bucket: "day" },
  "30d": { label: "Last 30 days", shortLabel: "30d", days: 30, bucket: "day" },
  "90d": { label: "Last 90 days", shortLabel: "90d", days: 90, bucket: "week" },
};

export const CHANNEL_META: Record<ConversationChannel, { label: string; description: string }> = {
  widget: { label: "Widget", description: "Embedded chat widget on your websites." },
  playground: { label: "Playground", description: "Test conversations from the chatbot playground." },
  api: { label: "API", description: "Conversations created through the API." },
  agent: { label: "Agent", description: "Conversations handled by agents." },
};

export const USAGE_KIND_META: Record<UsageKind, { label: string; description: string }> = {
  message: { label: "Messages", description: "Assistant replies generated." },
  tokens_in: { label: "Tokens in", description: "Prompt tokens sent to the model." },
  tokens_out: { label: "Tokens out", description: "Completion tokens generated by the model." },
  workflow_run: { label: "Workflow runs", description: "Workflow executions started." },
  embedding: { label: "Embeddings", description: "Chunks embedded for knowledge bases." },
  retrieval: { label: "Retrievals", description: "Knowledge lookups performed for answers." },
};

/** Ranked lists show this many named rows before collapsing the tail into "Other". */
export const TOP_CHATBOTS_LIMIT = 8;

/** Chatbots listed in the token breakdown table. */
export const TOKEN_TABLE_LIMIT = 10;

/** Billing is not live yet; every workspace is on the free plan. */
export const CURRENT_PLAN = { name: "Free", description: "Credits and subscriptions are coming soon." } as const;
